version: "3.7"

volumes:
  bundle:

services:
  package:
    build: .
    tty: true
    stdin_open: true
    working_dir: /home/package
    environment:
      - MEILISEARCH_URL=http://meilisearch:7700
      - MEILISEARCH_PORT=7700
      - BUNDLE_PATH=/vendor/bundle
    depends_on:
      - meilisearch
    links:
      - meilisearch
    ports:
      - "3001:3000"
    volumes:
      - bundle:/vendor/bundle
      - ./:/home/package
      # - ../meilisearch-ruby:/home/meilisearch-ruby

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
